### ISSUE TITLE
Build failure with Intel

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas#340]
### What happened?

Building with ifort (v19) fails with an ICE.

### What are the steps to reproduce the bug?

Buidl with ifort

### Version

HEAD

### Platform (OS and architecture)

Linux

### Relevant log output

```shell
[1/650] /data/apps/fortran/intel/composer_xe_2019.0.117/compilers_and_libraries_2019.0.117/linux/bin/intel64/ifort  -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src/tests/redistribution -I/home/users/david.davies/cylc-run/mo-bundle-866/share/mo-bundle/atlas/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src/atlas_f -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/module -I/home/users/david.davies/cylc-run/mo-bundle-866/share/mo-bundle/fckit/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/fckit/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/fckit/module -DINTEL -diag-disable=5462 -O3 -DNDEBUG -unroll -inline -heap-arrays 32 -module atlas/module -fPIE -c atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90-pp.f90 -o atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90.o
FAILED: atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90.o atlas/module/fcta_redistribution.mod atlas/module/fcta_redistribution_fxt.mod 
/data/apps/fortran/intel/composer_xe_2019.0.117/compilers_and_libraries_2019.0.117/linux/bin/intel64/ifort  -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src/tests/redistribution -I/home/users/david.davies/cylc-run/mo-bundle-866/share/mo-bundle/atlas/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/src/atlas_f -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/atlas/module -I/home/users/david.davies/cylc-run/mo-bundle-866/share/mo-bundle/fckit/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/fckit/src -I/home/users/david.davies/cylc-run/mo-bundle-866/share/make_mo_base__spice_intel/fckit/module -DINTEL -diag-disable=5462 -O3 -DNDEBUG -unroll -inline -heap-arrays 32 -module atlas/module -fPIE -c atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90-pp.f90 -o atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90.o
atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90-pp.f90: catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for atlas/src/tests/redistribution/CMakeFiles/atlas_fctest_redistribution.dir/fctest_redistribution_main.F90-pp.f90 (code 1)
```

### Organisation

Met Office

**Comment by wdeconinck** [comment]
Hi @DJDavies2 do you have actual requirements for this compiler?
More recent versions of "classic" intel compiler have no issue, and is already deprecated in favour of "llvm" based intel compiler.

**Comment by DJDavies2** [comment]
We don't have a more recent version at the moment.  Hopefully we will get something later in due course but at the moment this is the best we have.

**Comment by DJDavies2** [comment]
I've raised a PR that addresses this, what do you think?

**Comment by wdeconinck** [comment]
@DJDavies2 I have just disabled the test from compiling altogether with Intel Fortran < 19.1 instead. Now in develop and to be released in 0.45.1

**Comment by AlexanderRichert-NOAA** [comment]
Has atlas 0.45.1 or more recent been tested to build with Intel 19? With 19.1.3.304 I get a couple errors that look like:
```console
src/atlas/array/ArrayViewVariant.cc(48): error: no suitable user-defined conversion from "atlas::array::ArrayView<float, 1>" to "atlas::array::<un
             named>::VariantType<atlas::array::Array>" exists
     1148          return makeView(array, Value{}, std::integral_constant<int, Rank>{});
     1149                 ^
     1150              detected during:
     1151                instantiation of "atlas::array::<unnamed>::VariantType<ArrayType> atlas::array::<unnamed>::executeMakeView(ArrayType &, const MakeView &) [with TypeIndex=0UL, Arr
             ayType=atlas::array::Array, MakeView=lambda [](auto &, auto, auto)->auto]" at line 66
     1152                instantiation of "atlas::array::<unnamed>::VariantType<ArrayType> atlas::array::<unnamed>::makeViewVariantImpl(ArrayType &) [with ArrayType=atlas::array::Array]" 
             at line 88
```

**Comment by wdeconinck** [comment]
Hello @AlexanderRichert-NOAA we don't test this compiler anymore. If it is a requirement, please open a new issue to track this.
It is @odlomax who should then look into this if possible.
